Pod identity version update
mspnp/aks-baseline pull request #340
Opened 2022-08-16 18:51 UTC by v-fearam

https://github.com/Azure/aad-pod-identity/releases
https://azure.github.io/aad-pod-identity/changelog/
https://azure.github.io/aad-pod-identity/docs/

It was upadated the pod identity image, but not breking change was defined.

2022-08-16 19:23 UTC, ckittel requested changes
Missing a core security change in the manifest files for mic - https://github.com/Azure/aad-pod-identity/pull/1225  `readOnlyRootFilesystem: true`.  Guessing you didn't regenerate them as per our standard way of updating these?

Otherwise didn't see anything else in the manifest file changes that mattered

2022-08-17 11:24 UTC, v-fearam commented
> Missing a core security change in the manifest files for mic - [Azure/aad-pod-identity#1225](https://github.com/Azure/aad-pod-identity/pull/1225) `readOnlyRootFilesystem: true`.
> 
> Otherwise didn't see anything else in the manifest file changes that mattered

Changed, validated diff, and tested again

2022-08-17 12:50 UTC, ckittel commented on cluster-manifests/cluster-baseline-settings/aad-pod-identity.yaml
> +  # https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.8.11/deploy/infra/deployment-rbac.yaml
Nice touch!

2022-08-17 12:50 UTC, ckittel approved these changes

2022-08-17 12:50 UTC, merged